name: mutesitedeep
channels:
  - conda-forge
  - bioconda
dependencies: 
  - python=3.5
  - mongodb
  - blast
  - pip
  - pip: 
    - numpy
    - scipy
    - scikit-learn
    - pillow
    - h5py
    - pandas
    - feedparser
    - pymongo
    - configparser
    - keras==2.2.4
    - tensorflow==1.12.0
