name: mutesitedeep
channels:
  - conda-forge
  - bioconda
  - pytorch
dependencies:
  - numpy
  - scipy
  - scikit-learn
  - pillow
  - h5py
  - pandas
  - mongodb
  - configparser
  - pymongo
  - feedparser
  - blast
  - keras
  - tensorflow
  - tensorflow-gpu
